name: Update README.md
on:
  push:
    branches: [master]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: unfor19/replacer-action@v1.0.2
        name: Update README.md file
        with:
          src-file-path: "src/help.txt"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
          git-commit-msg: "Updated readme.md"
          create-backup: false
